# This is based on the config @ tox-dev/tox ï¿¼

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
resources:
  repositories:
  - repository: tox
    type: github
    endpoint: ansible
    name: tox-dev/azure-pipelines-template
    ref: master


trigger:
  batch: true
  branches:
    include:
    - master
    - ref/tags/*


pr:
  branches:
    include:
    - master


variables:
  # PYTEST_ADDOPTS: "-v -v -ra --showlocals"
  PRE_COMMIT_HOME: $(Pipeline.Workspace)/pre-commit-cache




jobs:
- template: .azure-pipelines/tox.yml
  parameters:
    ansible_versions:
    - 29
    - 28
    - devel
    python_envs:
      38: [linux, macOs]
      py3: [linux]
      37: [linux, macOs]
      36: [linux, macOs]
      35: [linux, macOs]
