---
- name: Fixture
  hosts: all
  tasks:
    - name: Clone content repository
      ansible.builtin.git:
        repo: "{{ archive_services_repo_url }}"
        dest: /home/www
        accept_hostkey: true
        version: master
        update: false
      become: true
      become_user: nobody
      notify:
        - restart apache2
