---
- name: Fixture
  hosts: webservers
  vars:
    varset: varset
  tasks:
    - block:
        - ansible.builtin.include_tasks: tasks/nestedincludes.yml
        # - block:
        #     - include_tasks: "{{ varnotset }}.yml"
      rescue:
        - ansible.builtin.include_tasks: "{{ varset }}.yml"
      always:
        - ansible.builtin.include_tasks: tasks/directory with spaces/main.yml
