---
- name: Fixture
  hosts: localhost
  vars:
    plain: hello123
    # spell-checker: disable-next-line
    # just 'hello123' encrypted with 'letmein' for test purposes
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      63346434613163653866303630313238626164313961613935373137323639636333393338386232
      3735313061316666343839343665383036623237353263310a623639336530383433343833653138
      30393032393534316164613834393864616566646164363830316664623636643731383164376163
      3736653037356435310a303533383533353739323834343637366438633766666163656330343631
      3066
  tasks:
    - name: Just a debug task
      ansible.builtin.debug:
        msg: hello world
