---
- name: Example playbook
  hosts: localhost
  tasks:
    - name: Write file content
      ansible.builtin.copy:
        content: { "foo": "bar" } # <-- avoid-implicit[copy-content]
        dest: /tmp/foo.txt
        mode: "0600"
