---
- name: Fixture for jinja2-template-extension (fail)
  hosts: localhost
  tasks:
    - name: Deploy config without .j2 extension # <-- 1st
      ansible.builtin.template:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        mode: "0644"

    - name: Deploy template with wrong extension # <-- 2nd
      ansible.builtin.template:
        src: app.conf.tmpl
        dest: /etc/myapp/app.conf
        mode: "0644"
