---
- name: Fixture
  hosts: localhost
  vars:
    varset: tasks/simple_task.yml
  tasks:
    # - include_tasks: "{{ varnotset }}.yml"
    - include_tasks: "{{ varset }}.yml"
    - include_tasks: tasks/directory with spaces/main.yml
    # Include tasks by FQCN as well to ensure they load
    - ansible.builtin.include_tasks: tasks/passing_task.yml
