---
- name: Fixture
  hosts: localhost
  vars:
    varset: tasks/simple_task.yml
  tasks:
    - import_tasks: tasks/nestedincludes.yml
    # - import_tasks: "{{ varnotset }}.yml"
    - import_tasks: "{{ varset }}"
    - import_tasks: tasks/directory with spaces/main.yml
    # Import tasks by FQCN as well to ensure they load
    - ansible.builtin.import_tasks: tasks/passing_task.yml
