---
- name: Fixture
  hosts: all
  tags:
    - skip_ansible_lint
  tasks:
    - name: Test hg-latest
      action: ansible.builtin.hg
    - name: Test hg-latest (skipped) # noqa hg-latest
      action: ansible.builtin.hg

    - name: Test git-latest and partial-become
      become_user: alice
      action: ansible.builtin.git
    - name: Test git-latest and partial-become (skipped) # noqa git-latest partial-become
      become_user: alice
      action: ansible.builtin.git

    - name: Test YAML and jinja[spacing]
      ansible.builtin.get_url:
        # noqa: risky-file-permissions
        url: http://example.com/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/file.conf
        dest: "{{dest_proj_path}}/foo.conf"
    - name: Test YAML and jinja[spacing] (skipped)
      ansible.builtin.get_url:
        # noqa: risky-file-permissions
        url: http://example.com/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/file.conf # noqa yaml
        dest: "{{dest_proj_path}}/foo.conf" # noqa jinja[spacing]

    - name: Test deprecated-command-syntax
      ansible.builtin.command: creates=B chmod 644 A
    - name: Test deprecated-command-syntax
      ansible.builtin.command: warn=yes creates=B chmod 644 A
    - name: Test deprecated-command-syntax (skipped via no warn)
      ansible.builtin.command: warn=no creates=B chmod 644 A
    - name: Test deprecated-command-syntax (skipped via skip_ansible_lint)
      ansible.builtin.command: creates=B chmod 644 A
      tags:
        - skip_ansible_lint

- name: Fixture 2
  hosts: localhost
  tasks:
    - name: Foo
      become: true
      block:
        - name: Bar
          become_user: john_doe
          ansible.builtin.command: "/etc/test.sh"
          changed_when: false
