---
# Used to validate that we also accept .yaml extension on playbooks
- name: Fixture
  hosts: localhost
  tasks:
    - ansible.builtin.debug: # <-- should notify about missing 'name'
        msg: hello!
