---
# meta file, determined by ending in meta/main.yml
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-dependencies
allow_duplicates: true
dependencies:
  # from Bitbucket
  - src: git+http://bitbucket.org/willthames/git-ansible-galaxy
    version: v1.4

  # from Bitbucket, alternative syntax and caveats
  - src: http://bitbucket.org/willthames/hg-ansible-galaxy
    scm: hg

  # from galaxy
  - src: yatesr.timezone

  # from GitHub
  - src: https://github.com/bennojoy/nginx

  # from GitHub, overriding the name and specifying a specific tag
  - src: https://github.com/bennojoy/nginx
    version: master
    name: nginx_role

  # from GitLab or other git-based scm
  - src: git@gitlab.company.com:my-group/my-repo.git
    scm: git
    version: "0.1" # quoted, so YAML doesn't parse this as a floating-point value

  # from a webserver, where the role is packaged in a tar.gz
  - src: https://some.webserver.example.com/files/master.tar.gz
    name: http-role

galaxy_info:
  standalone: true
  author: foo
  description: Testing meta
  company: Not applicable
  license: MIT
  min_ansible_version: "2.5"
  platforms:
    - name: Fedora
