---
# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false # default is true
contact_links:
  - name: Feature requests
    url: https://github.com/ansible/ansible-lint/discussions/categories/ideas
    about: Suggest an idea for this project
  - name: Discussions
    url: https://github.com/ansible/ansible-lint/discussions/
    about: Any kind of questions should go on the forum.
  - name: Security bug report
    url: https://docs.ansible.com/ansible/latest/community/reporting_bugs_and_features.html
    about: |
      Please learn how to report security vulnerabilities here.

      For all security related bugs, email security@ansible.com
      instead of using this issue tracker and you will receive
      a prompt response.

      For more information, see https://docs.ansible.com/ansible/latest/community/reporting_bugs_and_features.html
  - name: Ansible Code of Conduct
    url: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html
    about: Be nice to other members of the community. Behave.
