---
name: ack
on: # <-- ansible-lint should not complain or touch about this 'on'
  pull_request_target:
    types: [opened]

jobs:
  ack:
    uses: ansible/team-devtools/.github/workflows/ack.yml@main
