---
CamelCaseIsBad: false # invalid
this_is_valid: # valid because content is a dict, not a variable
  CamelCase: ...
  ALL_CAPS: ...
ALL_CAPS_ARE_BAD_TOO: ... # invalid
"{{ 'test_' }}var": "value" # noqa: schema
CamelCaseButErrorIgnored: true # noqa: var-naming
assert: true # invalid due to being Python reserved keyword
Ã©: true # invalid due to non-ascii character
hosts: true # invalid as being Ansible reserved name
